[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Friendlier paths for the Stripe endpoints
[[redirects]]
  from = "/api/checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/payment-intent"
  to = "/.netlify/functions/create-payment-intent"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/api/check-apple-pay"
  to = "/.netlify/functions/check-apple-pay"
  status = 200
